### ISSUE TITLE
Suggestion about memory capacity

### ISSUE THREAD

**Issue by ajtruckle** [ChristophePichaud/SystemInfoGUI#1]
I have come up with this:

	ManagementClass mc5(_TEXT("Win32_PhysicalMemory"));
	result = mc5.GetInstances();
	double installedRAM = 0.0;
	while (mc5.MoveNext())
	{
		installedRAM += _ttof(mc5.GetStringProperty(_TEXT("Capacity")));
	}
	const double usuableRAM = _ttof(mc2.GetStringProperty(_TEXT("TotalPhysicalMemory")));
	m_strSystemInfo.AppendFormat(L"  Installed RAM: %0.2f GB (%0.02f GB usable)\r\n",
		installedRAM / (1024.0 * 1024.0 * 1024.0),
		usuableRAM / (1024.0 * 1024.0 * 1024.0)
		);

	MEMORYSTATUSEX memstatus{}; memstatus.dwLength = sizeof(memstatus);
	if (GlobalMemoryStatusEx(&memstatus))
	{
		m_strSystemInfo.AppendFormat(L"  %s: %d%%\r\n", L"Current RAM in use", memstatus.dwMemoryLoad);
	}

Not yet worked out the new way to do _Current RAM in use_.

**Comment by ajtruckle** [comment]
Worked out the latter bit:

```
const auto freeRAM = _ttof(mcOperatingSystem.GetStringProperty(_TEXT("FreePhysicalMemory"))) * 1024.0; // bytes
const auto usedRAMPercent = (((usuableRAM - freeRAM)) / usuableRAM) * 100.0;
strHardwareInfo.AppendFormat(L"  Current RAM in use: %0.2f%%\r\n", usedRAMPercent);
```

**Comment by ChristophePichaud** [comment]
Yes it's cool.
My way is a little bit to few, reckless with:

                m_data.m_TotalMemory = mc.GetStringProperty(_TEXT("TotalPhysicalMemory"));

Yes, available memory is required.

I am currently an Emergency " Ambulancier " (french word) and unless working, sleeping and eating and having rest, I have no life with this new job since 5 weeks.

Just fork. Make improvement(s) and just do it!

Regards
Chris 🇫🇷😘
